"""empty message

Revision ID: fb52a30b7570
Revises: 4404557416cf
Create Date: 2026-03-30 13:12:04.289916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb52a30b7570'
down_revision = '4404557416cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('spaceships_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['spaceships_id'], ['spaceships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spaceships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pilot_id', sa.Integer(), nullable=True))
        batch_op.alter_column('afiliation',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'pilots', ['pilot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaceships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('afiliation',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('pilot_id')

    op.drop_table('favorites')
    # ### end Alembic commands ###
